// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  intro_slice: dynamic(() => import("./IntroSlice")),
  profile_picture: dynamic(() => import("./ProfilePicture")),
  quote: dynamic(() => import("./Quote")),
  tag_cloud: dynamic(() => import("./TagCloud")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
}
